spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mezhinjp2.beget.tech:3306/mezhinjp2_mfr?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: mezhinjp2_mfr
    password: 4eQ6Nr4O8&7Z

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8099